@startuml

title Packages - Component Diagram

rectangle "Web client" {
    component [User Interface] as GUI
}

cloud Internet {
}
 
node "traefik" {
    interface "websecure:9443" as access
    interface "basic-auth" as auth
} 

component "jasserver1:8080" <<golang:latest>> as jasserver1
component "jasserver2:8080" <<golang:latest>> as jasserver2
component "jasstatic1:80" <<nginx:alpine>> as jasstatic1
component "jasstatic2:80" <<nginx:alpine>> as jasstatic2

database "Database" <<postgres:latest>> {
    [jassdb:5432] as jassdb
}


GUI -down-> Internet
Internet -down-( auth
auth -down-( access
access -down- jasstatic1 :/
access -down- jasstatic2 :/
access -down- jasserver1 :/v1
access -down- jasserver2 :/v1
jasserver1 .. [jassdb]
jasserver2 .. [jassdb]

@enduml