@startuml

rectangle "Web client" {
    component [User Interface] as GUI
}

cloud Internet {
}

node "traefik" {
    interface "websecure:9443" as access
    interface "basic-auth" as auth
}

node "golang:latest" as golang1 {
    component "jasserver1:8080"  as jasserver1
}
node "golang:latest" as golang2 {
    component "jasserver2:8080" as jasserver2
}
node "nginx:alpine" as nginx1 {
    component "jasstatic1:80"  as jasstatic1
}
node "nginx:alpine" as nginx2 {
    component "jasstatic2:80" as jasstatic2
}

database "Database" <<postgres:latest>> {
    [jassdb:5432] as jassdb
}


GUI -down-> Internet
Internet -down-( auth
auth -down-( access
access -down- jasstatic1 :/
access -down- jasstatic2 :/
access -down- jasserver1 :/v1
access -down- jasserver2 :/v1
jasserver1 .. [jassdb]
jasserver2 .. [jassdb]

@enduml