@startuml ERD

object User {
    ID
    name
}

object Game {
    ID
    Team1
    Team2
    IsFinished
}

object Team {
    ID
    Name
}

object Round {
    ID
    Trumpf
}

object PointsPerTeamPerRound {
    ID
    WiisPoints
    Points
}

object Trumpf {
    ID
    Name
    Multiplier
}

User "1" -- "*" Game : creates >
Game "1" -- "*" Round : has >
Round "*" -- "1" Trumpf : has >
Round "1" -- "*" PointsPerTeamPerRound
Team "1" -- "*" PointsPerTeamPerRound

@enduml