@startuml ERD

object User {
    name
}

object Game {
    ID
}

object Team {
    Name
    Hundreds
    Fifties
    Twenties
    Rest
}

object Round {
    Trumpf
}

object PointsPerTeamPerRound {
    WiisPoints
    Points
}

object Trumpf {
    Name
    Multiplier
}

User "1" -- "m" Game : creates >
Game "1" -- "m" Round : has >
Round "1" -- "1" Trumpf : has >
Round "1" -- "1" PointsPerTeamPerRound
Team "1" -- "1" PointsPerTeamPerRound

@enduml