@startuml ERD

object User {
    name
}

object Game {
    ID
}

object Team {
    Name
}

object Round {
    Trumpf
}

object PointsPerTeamPerRound {
    WiisPoints
    Points
}

object Trumpf {
    Name
    Multiplier
}

User "1" -- "*" Game : creates >
Game "1" -- "*" Round : has >
Round "*" -- "1" Trumpf : has >
Round "1" -- "*" PointsPerTeamPerRound
Team "1" -- "*" PointsPerTeamPerRound

@enduml