networks:
  jassnet:
    attachable: true
    driver: bridge
    name: jassnet

x-env: &dflt-env
  # TZ format: https://pubs.opengroup.org/onlinepubs/007904975/basedefs/xbd_chap08.html
  TZ: CET-1CEST,M3.5.0,M10.5.0/3

services:
# tag::postgres[]
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=jass
    networks:
      jassnet: null
    ports:
      - 5433:5432
    volumes: 
      - jassdb-data:/var/lib/postgresql/data/ #persist data
      - ./jassdb.pgsql:/docker-entrypoint-initdb.d/init.sql
# end::postgres[]
# tag::traefik1[]
  traefik:
    hostname: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:9080"
      - "--entrypoints.websecure.address=:9443"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.filePath=/var/log/traefikAccesslog.log"
      - "--log.filePath=/var/log/traefik.log"
    image: traefik:latest
    networks:
      jassnet: null
    ports:
      - 8080:8080
      - 9080:9080
      - 9443:9443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
# end::traefik1[]
# tag::jasserver1[]
  jasserver1:
    hostname: jasserver1.docker.localhost
    build:
      context: ./
      dockerfile: jasserver/Dockerfile
    image: jasserver/jasserver:latest
    networks:
      jassnet: null
    ports:
      - 8888:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jasserver1.rule=PathPrefix(`/v1/`)"
      - "traefik.http.routers.jasserver1.entrypoints=websecure"
      - "traefik.http.services.jasservice.loadbalancer.server.port=8080"
      - "traefik.docker.network=jassnet"
      - "traefik.http.routers.jasserver1.middlewares=jass-auth"
      - "traefik.http.middlewares.jass-auth.basicauth.users=moe:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/,test2:$$apr1$$d9hr9HBB$$4HxwgUir3HP4EsggP/QNo0"
      - "traefik.http.middlewares.jass-auth.basicauth.realm=jassRealm"
      - "traefik.http.middlewares.jass-auth.basicauth.headerField=X-WebAuth-User"
# end::jasserver1[]
# tag::jasserver2[]
  jasserver2:
    hostname: jasserver2.docker.localhost
    build:
      context: ./
      dockerfile: jasserver/Dockerfile
    image: jasserver/jasserver:latest
    networks:
      jassnet: null
    ports:
      - 8889:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jasserver2.rule=PathPrefix(`/v1/`)"
      - "traefik.http.routers.jasserver2.entrypoints=websecure"
      - "traefik.http.services.jasservice.loadbalancer.server.port=8080"
      - "traefik.docker.network=jassnet"
      - "traefik.http.routers.jasserver2.middlewares=jass-auth"
      - "traefik.http.middlewares.jass-auth.basicauth.users=moe:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/,test2:$$apr1$$d9hr9HBB$$4HxwgUir3HP4EsggP/QNo0"
      - "traefik.http.middlewares.jass-auth.basicauth.realm=jassRealm"
      - "traefik.http.middlewares.jass-auth.basicauth.headerField=X-WebAuth-User"
# end::jasserver2[]
# tag::jasstatic1[]
  jasstatic1:
    container_name: jasstatic1.docker.localhost
    build:
      context: .
      # the dockerfile to be run
      dockerfile:
        ./jass/SPA_Dockerfile
    ports:
      - 3000:80
    networks:
      jassnet: null
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jasstatic1.rule=PathPrefix(`/`)"
      - "traefik.http.routers.jasstatic1.entrypoints=websecure"
      - "traefik.http.services.jasstatic.loadbalancer.server.port=80"
      - "traefik.docker.network=jassnet"
      - "traefik.http.routers.jasstatic1.middlewares=jass-auth"
      - "traefik.http.middlewares.jass-auth.basicauth.users=moe:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/,test2:$$apr1$$d9hr9HBB$$4HxwgUir3HP4EsggP/QNo0"
      - "traefik.http.middlewares.jass-auth.basicauth.realm=jassRealm"
      - "traefik.http.middlewares.jass-auth.basicauth.headerField=X-WebAuth-User"
# end::jasstatic1[]
# tag::jasstatic2[]
  jasstatic2:
    container_name: jasstatic2.docker.localhost
    build:
      context: .
      # the dockerfile to be run
      dockerfile:
        ./jass/SPA_Dockerfile
    ports:
      - 3001:80
    networks:
      jassnet: null
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jasstatic2.rule=PathPrefix(`/`)"
      - "traefik.http.routers.jasstatic2.entrypoints=websecure"
      - "traefik.http.services.jasstatic.loadbalancer.server.port=80"
      - "traefik.docker.network=jassnet"
      - "traefik.http.routers.jasstatic2.middlewares=jass-auth"
      - "traefik.http.middlewares.jass-auth.basicauth.users=moe:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/,test2:$$apr1$$d9hr9HBB$$4HxwgUir3HP4EsggP/QNo0"
      - "traefik.http.middlewares.jass-auth.basicauth.realm=jassRealm"
      - "traefik.http.middlewares.jass-auth.basicauth.headerField=X-WebAuth-User"
# end::jasstatic2[]

version: '3.6'
volumes:
    mongod1-data: {}
    golang-data: {}
    jassdb-data: {}